workflows:
  android-debug:
    name: Android Debug APK
    environment:
      java: 17
    scripts:
      - name: Install
        script: |
          npm ci || npm install
      - name: Sync
        script: |
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
